import de.fayard.refreshVersions.core.StabilityLevel

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.7.1/userguide/multi_project_builds.html
 */

rootProject.name = "auditor-v1"
include(
    "core",
    "client",
    "client-spring-boot-starter",
    "client-example",
    "client-example-springboot",
    "app",
)
plugins {
    val refreshVersions = "0.60.5"
    id("de.fayard.refreshVersions") version refreshVersions
}

refreshVersions {
    rejectVersionIf {
        candidate.stabilityLevel != StabilityLevel.Stable
    }
}
